metadata = {
        'email':{"type":"string"},
        'password':{"type":"string"},
        'uid':{'type':'integer'},
        'customer_id':{'type':'integer'},
        'model_id':{'type':'integer'},
        'currentPage':{'type':'integer'},
        'rowsCountPerTable':{'type':'integer'},
        'user_id':{'type':'integer'},
        'userid':{'type':'integer'},
        'column_id':{'type':'integer'},
        'sort_order':{'type':'integer'},
        'model_name':{'type':'string'},
        'tab_name':{'type':'string'},
        'day':{'type':'string'},
        'freq_time':{'type':'string'},
        'Type':{'type':'string'},
        'key':{'type':'string'},
        'start_date':{'type':'string'},
        "subscriptions":{"type":"list", "value_type":"string"},
        "filter":{"type":"list", "value_type":"string"},
        "cost_types":{"type":"list", "value_type":"string"},
        "resource_types":{"type":"list", "value_type":"string"},
        "uid":{"type":"integer", "maximum":15, "minimum":0},
        "cust_id":{"type":"integer", "maximum":190, "minimum":0},
        "cust_name":{"type":"string", "values":["TATASTEEL","TATASTEEL LP","TATASTEEL (KALIMATI)","Startek","ABMF","HGS CSE Citrix","ABSLi","Aditya Birla Group","HGS CES","IIFL","Firstsource Solutions Ltd","Mumbai Ops","BCP_DaaS","Anunta BLR","COE Team","HGS Healthcare - Prism","HGS - India VMWare","HGS-US","Medikigai","VMW TAP - BLR Team","VMW-AVD-Compete-BLR team","VMW-WS1-Compete-BLR team","Dr. Reddy's Laboratories Ltd","DR_MaximSoftware","DR_Auctusgroup","DR_TowerMSA","DR_TranTax","SW_WDV/TESTING","DR_Production_Control plane","Presales_Demo & Trial","PDM/COE/Field_TESTING","DR_Dev/QA/Demo","DR_Zenworx","ABFRL","Anunta Dev","Verbinden","DR_SAXLLP","DR_MPA MEDIA","Managing Patners","InfoSync","FPC_Dev/QA/Demo","EUV_Dev/QA/Demo","Cloud Optimal","National Grid","HGS ThinScale","DR_MaximSoftware_CA","EUVantage NA2","Argus","County of San Mateo","Carhartt","Dr_SW_AVD", "DR- SIG Image Gallery", "RG Reader POC Testing","Anunta QA", "Parker Hannifin", "DR_Pyramid solutions", "Etisalat_ Production_Control plane", "DR_ Durante Equipment", "Software AVD", "Ops Assistant Control Plane"]},
        "userid":{"type":"integer", "maximum":270, "minimum":0},
        "date":{"type":"multiple", "allowed_types":["string", "list"], "value_type":["string", "list"]},
        "cust":{"type":"string", "values":{"TATASTEEL","TATASTEEL LP","TATASTEEL (KALIMATI)","Startek","ABMF","HGS CSE Citrix","ABSLi","Aditya Birla Group","HGS CES","IIFL","Firstsource Solutions Ltd","Mumbai Ops","BCP_DaaS","Anunta BLR","COE Team","HGS Healthcare - Prism","HGS - India VMWare","HGS-US","Medikigai","VMW TAP - BLR Team","VMW-AVD-Compete-BLR team","VMW-WS1-Compete-BLR team","Dr. Reddy's Laboratories Ltd","DR_MaximSoftware","DR_Auctusgroup","DR_TowerMSA","DR_TranTax","SW_WDV/TESTING","DR_Production_Control plane","Presales_Demo & Trial","PDM/COE/Field_TESTING","DR_Dev/QA/Demo","DR_Zenworx","ABFRL","Anunta Dev","Verbinden","DR_SAXLLP","DR_MPA MEDIA","Managing Patners","InfoSync","FPC_Dev/QA/Demo","EUV_Dev/QA/Demo","Cloud Optimal","National Grid","HGS ThinScale","DR_MaximSoftware_CA","EUVantage NA2","Argus","County of San Mateo","Carhartt","Dr_SW_AVD", "DR- SIG Image Gallery", "RG Reader POC Testing","Anunta QA", "Parker Hannifin", "DR_Pyramid solutions", "Etisalat_ Production_Control plane", "DR_ Durante Equipment", "Software AVD", "Ops Assistant Control Plane"}},
        "customer_name":{"type":"string", "values":{"TATASTEEL","TATASTEEL LP","TATASTEEL (KALIMATI)","Startek","ABMF","HGS CSE Citrix","ABSLi","Aditya Birla Group","HGS CES","IIFL","Firstsource Solutions Ltd","Mumbai Ops","BCP_DaaS","Anunta BLR","COE Team","HGS Healthcare - Prism","HGS - India VMWare","HGS-US","Medikigai","VMW TAP - BLR Team","VMW-AVD-Compete-BLR team","VMW-WS1-Compete-BLR team","Dr. Reddy's Laboratories Ltd","DR_MaximSoftware","DR_Auctusgroup","DR_TowerMSA","DR_TranTax","SW_WDV/TESTING","DR_Production_Control plane","Presales_Demo & Trial","PDM/COE/Field_TESTING","DR_Dev/QA/Demo","DR_Zenworx","ABFRL","Anunta Dev","Verbinden","DR_SAXLLP","DR_MPA MEDIA","Managing Patners","InfoSync","FPC_Dev/QA/Demo","EUV_Dev/QA/Demo","Cloud Optimal","National Grid","HGS ThinScale","DR_MaximSoftware_CA","EUVantage NA2","Argus","County of San Mateo","Carhartt","Dr_SW_AVD", "DR- SIG Image Gallery", "RG Reader POC Testing","Anunta QA", "Parker Hannifin", "DR_Pyramid solutions", "Etisalat_ Production_Control plane", "DR_ Durante Equipment", "Software AVD", "Ops Assistant Control Plane"}},
        "tdata":{"type":"list", "value_type":"dictionary", "key_type":"string"},
        "customer":{"type":"string", "values":{"TATASTEEL","TATASTEEL LP","TATASTEEL (KALIMATI)","Startek","ABMF","HGS CSE Citrix","ABSLi","Aditya Birla Group","HGS CES","IIFL","Firstsource Solutions Ltd","Mumbai Ops","BCP_DaaS","Anunta BLR","COE Team","HGS Healthcare - Prism","HGS - India VMWare","HGS-US","Medikigai","VMW TAP - BLR Team","VMW-AVD-Compete-BLR team","VMW-WS1-Compete-BLR team","Dr. Reddy's Laboratories Ltd","DR_MaximSoftware","DR_Auctusgroup","DR_TowerMSA","DR_TranTax","SW_WDV/TESTING","DR_Production_Control plane","Presales_Demo & Trial","PDM/COE/Field_TESTING","DR_Dev/QA/Demo","DR_Zenworx","ABFRL","Anunta Dev","Verbinden","DR_SAXLLP","DR_MPA MEDIA","Managing Patners","InfoSync","FPC_Dev/QA/Demo","EUV_Dev/QA/Demo","Cloud Optimal","National Grid","HGS ThinScale","DR_MaximSoftware_CA","EUVantage NA2","Argus","County of San Mateo","Carhartt","Dr_SW_AVD", "DR- SIG Image Gallery", "RG Reader POC Testing","Anunta QA", "Parker Hannifin", "DR_Pyramid solutions", "Etisalat_ Production_Control plane", "DR_ Durante Equipment", "Software AVD", "Ops Assistant Control Plane", 'SCBINOZ91829', 'SCBBCUS85918', 'SCBADIT78872', 'SCBMKTE22815'}},
        "tag_name":{"type":["string", "list"]},
        "selected_values":{"type":"list"},
        "tag_id":{"type":["list", "string"]},
        "tag_name_old":{"type":"string"},
        "date":{"type":"string", "value_type":"list"},
        "CustomTag":{"type":"list", "value_type":"string"},
        "email":{"type":"string"},
        "password":{"type":"string"},
        "uid":{"type":"integer", "maximum":15, "minimum":0},
        "cust_id":{"type":"integer", "maximum":190, "minimum":0},
        "cust_name":{"type":"string", "values":["TATASTEEL","TATASTEEL LP","TATASTEEL (KALIMATI)","Startek","ABMF","HGS CSE Citrix","ABSLi","Aditya Birla Group","HGS CES","IIFL","Firstsource Solutions Ltd","Mumbai Ops","BCP_DaaS","Anunta BLR","COE Team","HGS Healthcare - Prism","HGS - India VMWare","HGS-US","Medikigai","VMW TAP - BLR Team","VMW-AVD-Compete-BLR team","VMW-WS1-Compete-BLR team","Dr. Reddy's Laboratories Ltd","DR_MaximSoftware","DR_Auctusgroup","DR_TowerMSA","DR_TranTax","SW_WDV/TESTING","DR_Production_Control plane","Presales_Demo & Trial","PDM/COE/Field_TESTING","DR_Dev/QA/Demo","DR_Zenworx","ABFRL","Anunta Dev","Verbinden","DR_SAXLLP","DR_MPA MEDIA","Managing Patners","InfoSync","FPC_Dev/QA/Demo","EUV_Dev/QA/Demo","Cloud Optimal","National Grid","HGS ThinScale","DR_MaximSoftware_CA","EUVantage NA2","Argus","County of San Mateo","Carhartt","Dr_SW_AVD", "DR- SIG Image Gallery", "RG Reader POC Testing","Anunta QA", "Parker Hannifin", "DR_Pyramid solutions", "Etisalat_ Production_Control plane", "DR_ Durante Equipment", "Software AVD", "Ops Assistant Control Plane"]},
        "userid":{"type":"integer", "maximum":15, "minimum":0},
        "date":{"type":"multiple", "allowed_types":["string", "list"], "value_type":["string", "list"]},
    #"date":{"type":"multiple", "value_type":["string", "list"]},
        "filter_by":{"type":"string", "values":{"Default", "Daily", "Monthly"}},
        "subscriptions":{"type":"list", "value_type":"string"},
        "regions":{"type":"list", "value_type":"string"},
        "rproviders":{"type":"list", "value_type":"string"},
        "rprovider":{"type":"list", "value_type":"string"},
        "filter":{"type":"list", "value_type":"string"},
        "flag":{"type":"multiple", "allowed_types":["integer","list", "string"]},
        "domains":{"type":"list", "value_type":"string"},
        "sub_id":{"type":"string"},
    #"hostpools":{"type":"list", "value_type":"string"},
        "hostpools":{"type":"multiple", "allowed_types":["string","list"]},
        "key":{"type":"string"},
        "color_dict":{"type":"list", "value_type":"dictionary", "key_type":"string"},
        "date_str":{"type":"string"},
        "ykeys":{"type":"list", "value_type":"string"},
    #"customTag":{"type":"list", "value_type":"string"},
        "customTag":{"type":"multiple", "allowed_types":["string","list"]},
        "CustomTag":{"type":"multiple", "allowed_types":["string","list"]},
        "hostpool":{"type":["string", "list"]},
        "currentPage":{"type":"integer", "maximum":10**9, "minimum":1},
        "rowsCountPerTable":{"type":"multiple", "allowed_types":{"integer","string"}},
        "cust":{"type":"string", "values":{"TATASTEEL","TATASTEEL LP","TATASTEEL (KALIMATI)","Startek","ABMF","HGS CSE Citrix","ABSLi","Aditya Birla Group","HGS CES","IIFL","Firstsource Solutions Ltd","Mumbai Ops","BCP_DaaS","Anunta BLR","COE Team","HGS Healthcare - Prism","HGS - India VMWare","HGS-US","Medikigai","VMW TAP - BLR Team","VMW-AVD-Compete-BLR team","VMW-WS1-Compete-BLR team","Dr. Reddy's Laboratories Ltd","DR_MaximSoftware","DR_Auctusgroup","DR_TowerMSA","DR_TranTax","SW_WDV/TESTING","DR_Production_Control plane","Presales_Demo & Trial","PDM/COE/Field_TESTING","DR_Dev/QA/Demo","DR_Zenworx","ABFRL","Anunta Dev","Verbinden","DR_SAXLLP","DR_MPA MEDIA","Managing Patners","InfoSync","FPC_Dev/QA/Demo","EUV_Dev/QA/Demo","Cloud Optimal","National Grid","HGS ThinScale","DR_MaximSoftware_CA","EUVantage NA2","Argus","County of San Mateo","Carhartt","Dr_SW_AVD", "DR- SIG Image Gallery", "RG Reader POC Testing","Anunta QA", "Parker Hannifin", "DR_Pyramid solutions", "Etisalat_ Production_Control plane", "DR_ Durante Equipment", "Software AVD", "Ops Assistant Control Plane"}},
        "subs":{"type":"list", "value_type":"string"},
        "subs":{"type":"list", "value_type":"string"},
        "tz_list":{"type":"multiple", "allowed_types":["string","list"]},
        "hour":{"type":"integer", "maximum":23, "minimum":0},
        "rgrp":{"type":"string"},
        "hostPools":{"type":"list", "value_type":"string"},
        "sort_order":{"type":"inetger", "maximum":2, "minimum":0},
        "column_id":{"type":"inetger", "maximum":2, "minimum":-1},
        #"tab_name":{"type":"string", "values":{"desktop", "resources", "resource_group", "hostpool", "hourly_peak_concurrency", "tags"}},
    #"desktops":{"type":"list", "value_type":"string"},
        "desktops":{"type":"multiple", "allowed_types":["string","list"]},
        "users":{"type":"multiple", "allowed_types":["string","list"]},
    #"users":{"type":"list", "value_type":"string"},
        "desktop_val":{"type":"string"},
        "desktop":{"type":"list", "value_type":"string"},
        "rproviders":{"type":"list", "value_type":"string"},
        "user":{"type":"string"},
        "user_chid":{"type":"string"},
        "tags":{"type":"list", "value_type":"string"},
        "otp":{"type":"inetger", "maximum":999999, "minimum":0},
        "token":{"type":"string"},
        "fullname":{"type":"string"},
        "user_id":{"type":"inetger", "maximum":15, "minimum":0},
        "old_password":{"type":"string"},
        "new_password":{"type":"string"},
        "customer_id":{"type":"integer", "maximum":190, "minimum":0},
        }
